---
title: "Regional Cumulative Impacts"
author: "Jamie Afflerbach"
date: "2/28/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=F,warning=F)

options(scipen = 999,
        digits = 4)

library(rgdal)
library(dplyr)
library(raster)

wgs_crs <- CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0")

# set the mazu data_edit share based on operating system
dir_M             <- c('Windows' = '//mazu.nceas.ucsb.edu/ohi',
                       'Darwin'  = '/Volumes/ohi',    ### connect (cmd-K) to smb://mazu/ohi
                       'Linux'   = '/home/shares/ohi')[[ Sys.info()[['sysname']] ]]

ocean = raster(file.path(dir_M,'model/GL-NCEAS-Halpern2008/tmp/ocean.tif'))%>%
          crop(.,extent(-18040095,18040134,0,9020067))

writeRaster(ocean,filename = file.path(dir_M,'git-annex/mci-report/ocean_half.tif'))

```

```{r rgn_shapefiles}

bc  = readOGR('shapefiles','ohibc_rgn')%>%
      spTransform(CRS("+proj=moll +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +units=m +no_defs"))
ne  = readOGR('shapefiles','ohine_rgn')%>%
      spTransform(CRS("+proj=moll +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +units=m +no_defs"))

mci_rgns = readOGR(dsn = file.path(dir_M,'git-annex/mci-report/shapefiles'),layer = 'mci_rgns')%>%
    spTransform(CRS("+proj=moll +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +units=m +no_defs"))

```

```{r chi_data}

#read in from Mazu location: marine_threats/impact_layers_2013_redo/global_impact_model_2013/normalized_by_two_time_periods/averaged_by_num_ecosystems/by_threat

layers <- list.files(file.path(dir_M,'marine_threats/impact_layers_2013_redo/global_impact_model_2013/normalized_by_two_time_periods/averaged_by_num_ecosystems/by_threat'),full.names=T, pattern = '.tif$')[c(1:5,7,9:12,14,15)]

```

Iterate through each shapefile + pressure layer, clip out region, summary stats

We probably want to save maps for each region + layer. Maybe we can do it by region?

```{r clip}

rng <- raster(layer)%>%
        crop(ocean)%>%
        mask(usa_shp)

library(purrr)

getvals <- function(layer){
  
  vals = raster(layer)%>%
          crop(ocean)%>%
          raster::extract(mci_rgns,method = 'simple',progress='text')%>%
          setNames(mci_rgns@data$rgn_nam)
  
return(vals)
}

#list of all values within each region for each pressure
mci_prs_vals = map(layers,getvals)%>%
               setNames(basename(layers))%>%
               setNames(str_replace(names(.),"_combo.tif",""))

  save(mci_prs_vals, file=file.path(dir_M,"git-annex/mci-report/rgn_prs_values.RData"))
  #vals is the list, let's try to use map to calculate mean, max
  
  load(file.path(dir_M,"git-annex/mci-report/rgn_prs_values.RData"))
```

```{r}

# Get quantiles for each pressure layer


quant_func <- function(layer){
  
    vec<-unlist(layer)
    q = quantile(vec,probs = c(0.025,0.25,0.5,0.75,0.975))
    
    return(q)
}
library(data.table)
library(stringr)
#quants is a list of length 12, one for each pressure layer. Each layer has 5 quantiles
quants = map(mci_prs_vals,quant_func)
q = quants%>%
      as.data.frame()%>%
          t()%>%
          as.data.frame()%>%
          tibble::rownames_to_column()%>%
          mutate(pressure = str_replace(rowname,'_combo.tif',""))%>%
          rename(verylow = `2.5%`,
                 low     = `25%`,
                 medium  = `50%`,
                 high    = `75%`,
                 veryhigh = `97.5%`)%>%
          dplyr::select(pressure, verylow, low, medium, high, veryhigh)

```

```{r}

df = data.frame()

for (i in 1:12){
   
     #get the pressure name
     for( j in 1:25){
       
     pres_name = names(mci_prs_vals[i])
     region   = names(mci_prs_vals[[i]])[j]
     
     #select the values
      m = mci_prs_vals[[pres_name]][[j]]

  h = filter(q,pressure == pres_name)
  
   n <- c(length(m[m<=h$verylow]),
          length(m[m<=h$low & m>h$verylow]),
          length(m[m<=h$high & m>h$low]),
          length(m[m<=h$veryhigh & m>h$high]),
          length(m[m>h$veryhigh]))
   
   d = data.frame(n)%>%
        mutate(perc = round(n/length(m),3),
               cat = c("verylow","low","medium","high","veryhigh"),
               brk = c(0,2.5,25,75,97.5), #assigning breaks for plotting later
               pressure = pres_name,
               rgn = region,
               mean = round(mean(m),3),
               max = round(max(m),3))
     
    df = rbind(df,d) 
     }
 }

```

```{r}

all = df%>%
      dplyr::select(-n)
      # group_by(rgn,pressure)%>%
      # tidyr::spread(cat,perc)

```

```{r regions}
library(ggplot2)

#by region (Canada Atlantic)
ca = df%>%filter(rgn == "Canada Atlantic")

ca$cat <- factor(ca$cat, levels = rev(c("verylow","low","medium","high","veryhigh")))

ggplot(ca,aes(x = pressure,y = perc,fill = factor(cat)))+
         geom_bar(position = 'stack',stat = 'identity', alpha = 1) +
  scale_fill_manual(values = c('verylow' = '#4dac26',
                               'low' = '#b8e186', 
                               'medium' = '#f1b6da',
                               'high' = '#d01c8b',
                               'veryhigh'='#67001f'),
                     name = "Category",
                     labels = c("verylow","low","medium","high","veryhigh",
                    guide = guide_legend(reverse = TRUE))) +
    coord_flip()+
  labs(y = "Percent of region's area")
  


#by pressure

ddf = df%>%filter(pressure == "inorganic")
ddf$cat <- factor(ddf$cat, levels = rev(c("verylow","low","medium","high","veryhigh")))

ggplot(ddf,aes(x = rgn,y = perc,fill = factor(cat)))+
         geom_bar(position = 'stack',stat = 'identity', alpha = 1) +
  scale_fill_manual(values = c('verylow' = '#4dac26',
                               'low' = '#b8e186', 
                               'medium' = '#f1b6da',
                               'high' = '#d01c8b',
                               'veryhigh'='#67001f'),
                     name = "Category",
                     labels = c("verylow","low","medium","high","veryhigh",
                    guide = guide_legend(reverse = TRUE))) +
    coord_flip()+
  labs(y = "Percent of region's area")

+
  facet_wrap(~pressure)


```

Try to answer the questions:

1) Where is each threat the greatest?
- Look at maximum number, NON area weighted, across threats

2) What threats are greatest in each region?



